# Generated by Django 2.2.4 on 2019-08-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=200)),
                ('u_school', models.CharField(max_length=200)),
                ('u_major', models.CharField(max_length=200)),
                ('u_interest', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_company', models.CharField(max_length=200)),
                ('a_interset', models.CharField(max_length=200)),
                ('a_qone_q', models.TextField(max_length=1000)),
                ('a_qone', models.TextField(max_length=2000)),
                ('a_qtwo_q', models.TextField(max_length=1000)),
                ('a_qtwo', models.TextField(max_length=2000)),
                ('a_qthree_q', models.TextField(max_length=1000)),
                ('a_qthree', models.TextField(max_length=2000)),
                ('a_qfour_q', models.TextField(max_length=1000)),
                ('a_four', models.TextField(max_length=2000)),
                ('a_qfive_q', models.TextField(max_length=1000)),
                ('a_five', models.TextField(max_length=2000)),
                ('a_nowuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle.Users')),
            ],
        ),
    ]
