# Generated by Django 2.2.4 on 2019-08-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='a_nowuser',
        ),
    ]
