# Generated by Django 2.2.4 on 2019-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middle', '0002_remove_apply_a_nowuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('name2', models.CharField(max_length=500)),
                ('videofile2', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('name3', models.CharField(max_length=500)),
                ('videofile3', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('name4', models.CharField(max_length=500)),
                ('videofile4', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('name5', models.CharField(max_length=500)),
                ('videofile5', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
