# Generated by Django 2.2.4 on 2019-08-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middle', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile4',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile5',
        ),
    ]
